const express = require("express");
const router = express.Router();
const Match = require("../models/Match");

// GET all matches, sorted by date
router.get("/", async (req, res) => {
  try {
    const matches = await Match.find().sort({ date: -1 });
    res.json(matches);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// GET only live matches
router.get("/live", async (req, res) => {
  try {
    const liveMatches = await Match.find({ status: "Live" });
    res.json(liveMatches);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

// POST to seed the database with comprehensive sample data
router.post("/seed", async (req, res) => {
  try {
    const sampleMatches = [
      // 1. Live Match: CSK chasing RCB's total (No Changes)
      {
        team1: {
          name: "Royal Challengers Bangalore",
          shortName: "RCB",
          players: [
            {
              name: "Virat Kohli",
              role: "batsman",
              runs: 55,
              balls: 40,
              status: "out",
            },
            {
              name: "Faf du Plessis",
              role: "batsman",
              runs: 25,
              balls: 20,
              status: "out",
            },
            {
              name: "Rajat Patidar",
              role: "batsman",
              runs: 12,
              balls: 10,
              status: "out",
            },
            {
              name: "Glenn Maxwell",
              role: "all-rounder",
              runs: 45,
              balls: 25,
              wickets: 1,
              oversBowled: "3.0",
              status: "yet-to-bat",
            },
            {
              name: "Dinesh Karthik",
              role: "wicket-keeper",
              runs: 26,
              balls: 12,
              status: "out",
            },
            {
              name: "Mahipal Lomror",
              role: "batsman",
              runs: 10,
              balls: 3,
              status: "yet-to-bat",
            },
            {
              name: "Shahbaz Ahmed",
              role: "all-rounder",
              runs: 0,
              balls: 0,
              wickets: 0,
              oversBowled: "2.0",
              status: "yet-to-bat",
            },
            {
              name: "Wanindu Hasaranga",
              role: "bowler",
              runs: 0,
              balls: 0,
              wickets: 2,
              oversBowled: "4.0",
              status: "yet-to-bat",
            },
            {
              name: "Harshal Patel",
              role: "bowler",
              runs: 0,
              balls: 0,
              wickets: 1,
              oversBowled: "3.2",
              status: "bowling",
            },
            {
              name: "Josh Hazlewood",
              role: "bowler",
              runs: 0,
              balls: 0,
              wickets: 2,
              oversBowled: "4.0",
              status: "yet-to-bat",
            },
            {
              name: "Mohammed Siraj",
              role: "bowler",
              runs: 0,
              balls: 0,
              wickets: 1,
              oversBowled: "4.0",
              status: "yet-to-bat",
            },
          ],
        },
        team2: {
          name: "Chennai Super Kings",
          shortName: "CSK",
          players: [
            {
              name: "Ruturaj Gaikwad",
              role: "batsman",
              runs: 28,
              balls: 23,
              status: "out",
            },
            {
              name: "Devon Conway",
              role: "batsman",
              runs: 3,
              balls: 5,
              status: "out",
            },
            {
              name: "Moeen Ali",
              role: "all-rounder",
              runs: 34,
              balls: 27,
              status: "out",
            },
            {
              name: "Shivam Dube",
              role: "all-rounder",
              runs: 25,
              balls: 18,
              status: "batting",
            },
            {
              name: "Ambati Rayudu",
              role: "batsman",
              runs: 15,
              balls: 10,
              status: "batting",
            },
            { name: "MS Dhoni", role: "wicket-keeper", status: "yet-to-bat" },
            {
              name: "Ravindra Jadeja",
              role: "all-rounder",
              status: "yet-to-bat",
            },
            { name: "Dwayne Bravo", role: "bowler", status: "yet-to-bat" },
            {
              name: "Maheesh Theekshana",
              role: "bowler",
              status: "yet-to-bat",
            },
            { name: "Mukesh Choudhary", role: "bowler", status: "yet-to-bat" },
            { name: "Simarjeet Singh", role: "bowler", status: "yet-to-bat" },
          ],
        },
        score1: 173,
        wickets1: 4,
        overs1: "20.0",
        score2: 125,
        wickets2: 3,
        overs2: "16.2",
        battingTeam: 2,
        status: "Live",
        venue: "M. Chinnaswamy Stadium, Bangalore",
        currentBowler: "Harshal Patel",
        currentBatsmen: ["Shivam Dube", "Ambati Rayudu"],
      },

      // 2. Completed Match: High-scoring thriller (UPDATED WITH FULL STATS)
      {
        team1: {
          name: "Rajasthan Royals",
          shortName: "RR",
          players: [
            {
              name: "Jos Buttler",
              role: "wicket-keeper",
              runs: 103,
              balls: 61,
              status: "out",
            },
            {
              name: "Devdutt Padikkal",
              role: "batsman",
              runs: 24,
              balls: 18,
              status: "out",
            },
            {
              name: "Sanju Samson",
              role: "wicket-keeper",
              runs: 46,
              balls: 19,
              status: "out",
            },
            {
              name: "Riyan Parag",
              role: "all-rounder",
              runs: 5,
              balls: 3,
              wickets: 0,
              oversBowled: "1.0",
              status: "out",
            },
            {
              name: "Karun Nair",
              role: "batsman",
              runs: 3,
              balls: 5,
              status: "out",
            },
            {
              name: "Shimron Hetmyer",
              role: "batsman",
              runs: 2,
              balls: 1,
              status: "yet-to-bat",
            },
            {
              name: "Ravichandran Ashwin",
              role: "bowler",
              runs: 0,
              balls: 0,
              wickets: 0,
              oversBowled: "4.0",
              status: "yet-to-bat",
            },
            {
              name: "Trent Boult",
              role: "bowler",
              runs: 0,
              balls: 0,
              wickets: 1,
              oversBowled: "4.0",
              status: "yet-to-bat",
            },
            {
              name: "Prasidh Krishna",
              role: "bowler",
              runs: 0,
              balls: 0,
              wickets: 1,
              oversBowled: "4.0",
              status: "yet-to-bat",
            },
            {
              name: "Yuzvendra Chahal",
              role: "bowler",
              runs: 0,
              balls: 0,
              wickets: 5,
              oversBowled: "4.0",
              status: "yet-to-bat",
            },
            {
              name: "Obed McCoy",
              role: "bowler",
              runs: 0,
              balls: 0,
              wickets: 2,
              oversBowled: "3.4",
              status: "yet-to-bat",
            },
          ],
        },
        team2: {
          name: "Kolkata Knight Riders",
          shortName: "KKR",
          players: [
            {
              name: "Aaron Finch",
              role: "batsman",
              runs: 58,
              balls: 28,
              status: "out",
            },
            {
              name: "Sunil Narine",
              role: "all-rounder",
              runs: 0,
              balls: 1,
              wickets: 2,
              oversBowled: "4.0",
              status: "out",
            },
            {
              name: "Shreyas Iyer",
              role: "batsman",
              runs: 85,
              balls: 51,
              status: "out",
            },
            {
              name: "Nitish Rana",
              role: "batsman",
              runs: 18,
              balls: 11,
              status: "out",
            },
            {
              name: "Andre Russell",
              role: "all-rounder",
              runs: 0,
              balls: 1,
              wickets: 1,
              oversBowled: "2.0",
              status: "out",
            },
            {
              name: "Venkatesh Iyer",
              role: "all-rounder",
              runs: 6,
              balls: 7,
              status: "out",
            },
            {
              name: "Sheldon Jackson",
              role: "wicket-keeper",
              runs: 2,
              balls: 2,
              status: "out",
            },
            {
              name: "Pat Cummins",
              role: "bowler",
              runs: 0,
              balls: 1,
              wickets: 1,
              oversBowled: "4.0",
              status: "out",
            },
            {
              name: "Shivam Mavi",
              role: "bowler",
              runs: 0,
              balls: 2,
              wickets: 1,
              oversBowled: "4.0",
              status: "out",
            },
            {
              name: "Umesh Yadav",
              role: "bowler",
              runs: 21,
              balls: 9,
              wickets: 0,
              oversBowled: "4.0",
              status: "out",
            },
            {
              name: "Varun Chakravarthy",
              role: "bowler",
              runs: 0,
              balls: 0,
              wickets: 0,
              oversBowled: "2.0",
              status: "yet-to-bat",
            },
          ],
        },
        score1: 217,
        wickets1: 5,
        overs1: "20.0",
        score2: 210,
        wickets2: 10,
        overs2: "19.4",
        status: "Completed",
        venue: "Brabourne Stadium, Mumbai",
      },

      // 3. Upcoming Match: Standard future fixture (No Changes)
      {
        team1: {
          name: "Sunrisers Hyderabad",
          shortName: "SRH",
          players: [
            { name: "Abhishek Sharma", role: "all-rounder" },
            { name: "Kane Williamson", role: "batsman" },
            { name: "Rahul Tripathi", role: "batsman" },
            { name: "Aiden Markram", role: "batsman" },
            { name: "Nicholas Pooran", role: "wicket-keeper" },
            { name: "Shashank Singh", role: "batsman" },
            { name: "Washington Sundar", role: "all-rounder" },
            { name: "Marco Jansen", role: "all-rounder" },
            { name: "Bhuvneshwar Kumar", role: "bowler" },
            { name: "T Natarajan", role: "bowler" },
            { name: "Umran Malik", role: "bowler" },
          ],
        },
        team2: {
          name: "Punjab Kings",
          shortName: "PBKS",
          players: [
            { name: "Shikhar Dhawan", role: "batsman" },
            { name: "Mayank Agarwal", role: "batsman" },
            { name: "Jonny Bairstow", role: "wicket-keeper" },
            { name: "Liam Livingstone", role: "all-rounder" },
            { name: "Jitesh Sharma", role: "wicket-keeper" },
            { name: "Shahrukh Khan", role: "batsman" },
            { name: "Rishi Dhawan", role: "all-rounder" },
            { name: "Kagiso Rabada", role: "bowler" },
            { name: "Rahul Chahar", role: "bowler" },
            { name: "Arshdeep Singh", role: "bowler" },
            { name: "Sandeep Sharma", role: "bowler" },
          ],
        },
        status: "Upcoming",
        venue: "Wankhede Stadium, Mumbai",
        date: new Date("2025-08-10T19:30:00"),
      },

      // 4. Live Match: Start of an innings (No Changes)
      {
        team1: {
          name: "Gujarat Titans",
          shortName: "GT",
          players: [
            {
              name: "Wriddhiman Saha",
              role: "wicket-keeper",
              runs: 5,
              balls: 7,
              status: "out",
            },
            {
              name: "Shubman Gill",
              role: "batsman",
              runs: 63,
              balls: 49,
              status: "out",
            },
            {
              name: "Hardik Pandya",
              role: "all-rounder",
              runs: 24,
              balls: 18,
              wickets: 1,
              oversBowled: "3.0",
              status: "out",
            },
            {
              name: "David Miller",
              role: "batsman",
              runs: 32,
              balls: 22,
              status: "yet-to-bat",
            },
            {
              name: "Rahul Tewatia",
              role: "all-rounder",
              runs: 22,
              balls: 15,
              wickets: 0,
              oversBowled: "1.0",
              status: "yet-to-bat",
            },
            {
              name: "Rashid Khan",
              role: "bowler",
              runs: 4,
              balls: 2,
              wickets: 2,
              oversBowled: "4.0",
              status: "yet-to-bat",
            },
            {
              name: "Sai Kishore",
              role: "bowler",
              runs: 0,
              balls: 0,
              wickets: 1,
              oversBowled: "4.0",
              status: "yet-to-bat",
            },
            {
              name: "Alzarri Joseph",
              role: "bowler",
              runs: 0,
              balls: 0,
              wickets: 1,
              oversBowled: "4.0",
              status: "yet-to-bat",
            },
            {
              name: "Yash Dayal",
              role: "bowler",
              runs: 0,
              balls: 0,
              wickets: 0,
              oversBowled: "2.0",
              status: "yet-to-bat",
            },
            {
              name: "Mohammed Shami",
              role: "bowler",
              runs: 0,
              balls: 0,
              wickets: 1,
              oversBowled: "4.0",
              status: "bowling",
            },
            {
              name: "Lockie Ferguson",
              role: "bowler",
              runs: 0,
              balls: 0,
              wickets: 0,
              oversBowled: "2.0",
              status: "yet-to-bat",
            },
          ],
        },
        team2: {
          name: "Lucknow Super Giants",
          shortName: "LSG",
          players: [
            {
              name: "KL Rahul",
              role: "batsman",
              runs: 12,
              balls: 8,
              status: "batting",
            },
            {
              name: "Quinton de Kock",
              role: "wicket-keeper",
              runs: 5,
              balls: 4,
              status: "batting",
            },
            { name: "Evin Lewis", role: "batsman", status: "yet-to-bat" },
            { name: "Deepak Hooda", role: "all-rounder", status: "yet-to-bat" },
            { name: "Ayush Badoni", role: "batsman", status: "yet-to-bat" },
            {
              name: "Marcus Stoinis",
              role: "all-rounder",
              status: "yet-to-bat",
            },
            {
              name: "Krunal Pandya",
              role: "all-rounder",
              status: "yet-to-bat",
            },
            { name: "Jason Holder", role: "all-rounder", status: "yet-to-bat" },
            {
              name: "Dushmantha Chameera",
              role: "bowler",
              status: "yet-to-bat",
            },
            { name: "Ravi Bishnoi", role: "bowler", status: "yet-to-bat" },
            { name: "Avesh Khan", role: "bowler", status: "yet-to-bat" },
          ],
        },
        score1: 168,
        wickets1: 6,
        overs1: "20.0",
        score2: 18,
        wickets2: 0,
        overs2: "2.0",
        battingTeam: 2,
        status: "Live",
        venue: "MCA Stadium, Pune",
        currentBowler: "Mohammed Shami",
        currentBatsmen: ["KL Rahul", "Quinton de Kock"],
      },

      // 5. Completed Match: Low-scoring, dominant win (UPDATED WITH FULL STATS)
      {
        team1: {
          name: "Delhi Capitals",
          shortName: "DC",
          players: [
            {
              name: "Prithvi Shaw",
              role: "batsman",
              runs: 41,
              balls: 20,
              status: "out",
            },
            {
              name: "David Warner",
              role: "batsman",
              runs: 60,
              balls: 30,
              status: "yet-to-bat",
            },
            {
              name: "Rishabh Pant",
              role: "wicket-keeper",
              runs: 7,
              balls: 8,
              status: "yet-to-bat",
            },
            {
              name: "Rovman Powell",
              role: "batsman",
              runs: 2,
              balls: 4,
              status: "out",
            },
            {
              name: "Lalit Yadav",
              role: "all-rounder",
              runs: 2,
              balls: 5,
              status: "yet-to-bat",
            },
            {
              name: "Axar Patel",
              role: "all-rounder",
              runs: 0,
              balls: 0,
              wickets: 2,
              oversBowled: "4.0",
              status: "yet-to-bat",
            },
            {
              name: "Shardul Thakur",
              role: "bowler",
              runs: 0,
              balls: 0,
              wickets: 0,
              oversBowled: "2.0",
              status: "yet-to-bat",
            },
            {
              name: "Kuldeep Yadav",
              role: "bowler",
              runs: 0,
              balls: 0,
              wickets: 2,
              oversBowled: "4.0",
              status: "yet-to-bat",
            },
            {
              name: "Mustafizur Rahman",
              role: "bowler",
              runs: 0,
              balls: 0,
              wickets: 1,
              oversBowled: "4.0",
              status: "yet-to-bat",
            },
            {
              name: "Khaleel Ahmed",
              role: "bowler",
              runs: 0,
              balls: 0,
              wickets: 2,
              oversBowled: "4.0",
              status: "yet-to-bat",
            },
            {
              name: "Anrich Nortje",
              role: "bowler",
              runs: 0,
              balls: 0,
              wickets: 0,
              oversBowled: "2.3",
              status: "yet-to-bat",
            },
          ],
        },
        team2: {
          name: "Punjab Kings",
          shortName: "PBKS",
          players: [
            {
              name: "Mayank Agarwal",
              role: "batsman",
              runs: 24,
              balls: 15,
              status: "out",
            },
            {
              name: "Shikhar Dhawan",
              role: "batsman",
              runs: 9,
              balls: 10,
              status: "out",
            },
            {
              name: "Jonny Bairstow",
              role: "wicket-keeper",
              runs: 9,
              balls: 8,
              status: "out",
            },
            {
              name: "Liam Livingstone",
              role: "all-rounder",
              runs: 2,
              balls: 3,
              wickets: 0,
              oversBowled: "2.0",
              status: "out",
            },
            {
              name: "Jitesh Sharma",
              role: "wicket-keeper",
              runs: 32,
              balls: 23,
              status: "out",
            },
            {
              name: "Shahrukh Khan",
              role: "batsman",
              runs: 12,
              balls: 20,
              status: "out",
            },
            {
              name: "Kagiso Rabada",
              role: "bowler",
              runs: 2,
              balls: 6,
              wickets: 1,
              oversBowled: "2.0",
              status: "out",
            },
            {
              name: "Nathan Ellis",
              role: "bowler",
              runs: 0,
              balls: 1,
              wickets: 0,
              oversBowled: "1.0",
              status: "out",
            },
            {
              name: "Rahul Chahar",
              role: "bowler",
              runs: 25,
              balls: 20,
              wickets: 0,
              oversBowled: "3.0",
              status: "out",
            },
            {
              name: "Vaibhav Arora",
              role: "bowler",
              runs: 2,
              balls: 6,
              wickets: 0,
              oversBowled: "2.0",
              status: "out",
            },
            {
              name: "Arshdeep Singh",
              role: "bowler",
              runs: 0,
              balls: 1,
              wickets: 0,
              oversBowled: "2.0",
              status: "yet-to-bat",
            },
          ],
        },
        score1: 115,
        wickets1: 10,
        overs1: "20.0",
        score2: 119,
        wickets2: 1,
        overs2: "10.3",
        status: "Completed",
        venue: "DY Patil Stadium, Navi Mumbai",
      },

      // 6. Upcoming Match: Toss done, about to start (No Changes)
      {
        team1: {
          name: "Mumbai Indians",
          shortName: "MI",
          players: [
            { name: "Rohit Sharma", role: "batsman" },
            { name: "Ishan Kishan", role: "wicket-keeper" },
            { name: "Dewald Brevis", role: "batsman" },
            { name: "Suryakumar Yadav", role: "batsman" },
            { name: "Tilak Varma", role: "batsman" },
            { name: "Kieron Pollard", role: "all-rounder" },
            { name: "Daniel Sams", role: "all-rounder" },
            { name: "Murugan Ashwin", role: "bowler" },
            { name: "Jasprit Bumrah", role: "bowler" },
            { name: "Tymal Mills", role: "bowler" },
            { name: "Basil Thampi", role: "bowler" },
          ],
        },
        team2: {
          name: "Chennai Super Kings",
          shortName: "CSK",
          players: [
            { name: "Ruturaj Gaikwad", role: "batsman" },
            { name: "Devon Conway", role: "batsman" },
            { name: "Moeen Ali", role: "all-rounder" },
            { name: "Shivam Dube", role: "all-rounder" },
            { name: "Ambati Rayudu", role: "batsman" },
            { name: "MS Dhoni", role: "wicket-keeper" },
            { name: "Ravindra Jadeja", role: "all-rounder" },
            { name: "Dwayne Bravo", role: "bowler" },
            { name: "Maheesh Theekshana", role: "bowler" },
            { name: "Mukesh Choudhary", role: "bowler" },
            { name: "Simarjeet Singh", role: "bowler" },
          ],
        },
        battingTeam: 1, // MI won the toss and chose to bat
        status: "Upcoming",
        venue: "Wankhede Stadium, Mumbai",
        date: new Date("2025-08-12T19:30:00"),
      },
    ];

    await Match.deleteMany({});
    await Match.insertMany(sampleMatches);
    res.json({ message: "Comprehensive sample data seeded successfully!" });
  } catch (error) {
    console.error("ERROR SEEDING DATA:", error);
    res.status(500).json({ message: error.message });
  }
});

module.exports = router;
